### ISSUE TITLE
Release a gem checklist Issue

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday-http#16]
This Issue is a sign-post issue 🚩  about things we need to have done before releasing this as a gem.

## TODO

- [x] Use GitHub Actions #14
- [x] GitHub Actions to publish gem
- [x] Drop CircleCI
- [ ] .github/*.md content from Faraday
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
- [x] Complete the README
- [x] Complete the gemspec
- [x] Release on RubyGems

**Comment by olleolleolle** [comment]
Released! 🥇
